// This file is generated by scripts/generate-api-contract.mjs. Do not edit.

import Foundation

struct AccountExportResponse: Codable, Equatable, Hashable, Sendable {
    var exportedAt: String
    var account: AccountExportAccount
    var packages: [Parcel]
}

struct DeleteAccountRequest: Codable, Equatable, Hashable, Sendable {
    var confirmation: String
}

struct CarrierID: RawRepresentable, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    let rawValue: String

    init(rawValue: String) {
        self.rawValue = rawValue
    }

    static let swissPost = CarrierID(rawValue: "swiss-post")
    static let swissPostCargo = CarrierID(rawValue: "swiss-post-cargo")
    static let quickpac = CarrierID(rawValue: "quickpac")
    static let planzer = CarrierID(rawValue: "planzer")
    static let aliexpress = CarrierID(rawValue: "aliexpress")
    static let sunyou = CarrierID(rawValue: "sunyou")
    static let hermes = CarrierID(rawValue: "hermes")
    static let springGDS = CarrierID(rawValue: "spring-gds")
    static let postlogistics = CarrierID(rawValue: "postlogistics")
    static let dachser = CarrierID(rawValue: "dachser")
    static let dhl = CarrierID(rawValue: "dhl")
    static let ups = CarrierID(rawValue: "ups")
    static let amazonLogistics = CarrierID(rawValue: "amazon-logistics")
    static let fedex = CarrierID(rawValue: "fedex")
    static let glsCh = CarrierID(rawValue: "gls-ch")
    static let dpd = CarrierID(rawValue: "dpd")
    static let dpdFr = CarrierID(rawValue: "dpd-fr")
    static let mondialRelay = CarrierID(rawValue: "mondial-relay")
    static let relaisColis = CarrierID(rawValue: "relais-colis")
    static let laPoste = CarrierID(rawValue: "la-poste")
    static let chronopost = CarrierID(rawValue: "chronopost")
    static let glsFr = CarrierID(rawValue: "gls-fr")
    static let colisPrive = CarrierID(rawValue: "colis-prive")
    static let geodis = CarrierID(rawValue: "geodis")
    static let colisweb = CarrierID(rawValue: "colisweb")
    static let cChezVous = CarrierID(rawValue: "c-chez-vous")
    static let heppner = CarrierID(rawValue: "heppner")
    static let ciblex = CarrierID(rawValue: "ciblex")
    static let paack = CarrierID(rawValue: "paack")
    static let asendia = CarrierID(rawValue: "asendia")
    static let shipup = CarrierID(rawValue: "shipup")
    static let internationalPost = CarrierID(rawValue: "intl-post")
    static let unknown = CarrierID(rawValue: "unknown")

    static let allCases: [CarrierID] = [
        .swissPost,
        .swissPostCargo,
        .quickpac,
        .planzer,
        .aliexpress,
        .sunyou,
        .hermes,
        .springGDS,
        .postlogistics,
        .dachser,
        .dhl,
        .ups,
        .amazonLogistics,
        .fedex,
        .glsCh,
        .dpd,
        .dpdFr,
        .mondialRelay,
        .relaisColis,
        .laPoste,
        .chronopost,
        .glsFr,
        .colisPrive,
        .geodis,
        .colisweb,
        .cChezVous,
        .heppner,
        .ciblex,
        .paack,
        .asendia,
        .shipup,
        .internationalPost,
        .unknown,
    ]

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    var id: String { rawValue }
}

enum TrackingStage: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case pending
    case registered
    case accepted
    case inTransit = "in_transit"
    case outForDelivery = "out_for_delivery"
    case delivered
    case customs
    case failedAttempt = "failed_attempt"
    case readyForPickup = "ready_for_pickup"
    case returned

    var id: String { rawValue }
}

enum SyncStatus: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case pending
    case syncing
    case ok
    case waiting
    case error
    case unsupported

    var id: String { rawValue }
}

struct TrackingEvent: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var packageID: UUID
    var stage: TrackingStage
    var description: String
    var location: String? = nil
    var occurredAt: String

    private enum CodingKeys: String, CodingKey {
        case id
        case packageID = "packageId"
        case stage
        case description
        case location
        case occurredAt
    }
}

struct Parcel: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var trackingNumber: String
    var label: String
    var carrier: CarrierID
    var createdAt: String
    var expectedDelivery: String? = nil
    var lastStatusText: String? = nil
    var lastSyncedAt: String? = nil
    var syncStatus: SyncStatus
    var syncError: String? = nil
    var trackingURL: String? = nil
    var dpdPostcode: String? = nil
    var carrierData: CarrierData? = nil
    var archivedAt: String? = nil
    var notificationsMuted: Bool
    var trackingEvents: [TrackingEvent] = []

    private enum CodingKeys: String, CodingKey {
        case id
        case trackingNumber
        case label
        case carrier
        case createdAt
        case expectedDelivery
        case lastStatusText
        case lastSyncedAt
        case syncStatus
        case syncError
        case trackingURL = "trackingUrl"
        case dpdPostcode
        case carrierData
        case archivedAt
        case notificationsMuted
        case trackingEvents
    }
}

struct PackageListResponse: Codable, Equatable, Hashable, Sendable {
    var packages: [Parcel]
}

struct CreatePackageResponse: Codable, Equatable, Hashable, Sendable {
    var package: Parcel
    var jobIDs: [UUID]

    private enum CodingKeys: String, CodingKey {
        case package
        case jobIDs = "jobIds"
    }
}

struct CreatePackageRequest: Codable, Equatable, Hashable, Sendable {
    var trackingNumber: String
    var label: String? = nil
    var carrier: CarrierID? = nil
    var trackingURL: String? = nil
    var dpdPostcode: String? = nil

    private enum CodingKeys: String, CodingKey {
        case trackingNumber
        case label
        case carrier
        case trackingURL = "trackingUrl"
        case dpdPostcode
    }
}

struct RenamePackageRequest: Codable, Equatable, Hashable, Sendable {
    var label: String
}

struct ChangePackageCarrierRequest: Codable, Equatable, Hashable, Sendable {
    var carrier: CarrierID
    var trackingURL: String? = nil
    var dpdPostcode: String? = nil

    private enum CodingKeys: String, CodingKey {
        case carrier
        case trackingURL = "trackingUrl"
        case dpdPostcode
    }
}

struct ChangePackageCarrierResponse: Codable, Equatable, Hashable, Sendable {
    var package: Parcel
    var jobIDs: [UUID]

    private enum CodingKeys: String, CodingKey {
        case package
        case jobIDs = "jobIds"
    }
}

struct PackageNotificationRequest: Codable, Equatable, Hashable, Sendable {
    var muted: Bool
}

struct QueueResponse: Codable, Equatable, Hashable, Sendable {
    var queued: Bool
    var pending: Int
    var jobIDs: [UUID]

    private enum CodingKeys: String, CodingKey {
        case queued
        case pending
        case jobIDs = "jobIds"
    }
}

struct OKResponse: Codable, Equatable, Hashable, Sendable {
    var ok: Bool
}

struct ErrorResponse: Codable, Equatable, Hashable, Sendable {
    var error: String
    var packageID: UUID? = nil

    private enum CodingKeys: String, CodingKey {
        case error
        case packageID = "packageId"
    }
}

struct PushConfigResponse: Codable, Equatable, Hashable, Sendable {
    var available: Bool
    var publicKey: String? = nil
}

enum NotificationStage: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case registered
    case accepted
    case inTransit = "in_transit"
    case customs
    case outForDelivery = "out_for_delivery"
    case failedAttempt = "failed_attempt"
    case readyForPickup = "ready_for_pickup"
    case delivered
    case returned

    var id: String { rawValue }
}

struct NotificationPreferences: Codable, Equatable, Hashable, Sendable {
    var enabledStages: [NotificationStage]
    var quietHoursStart: String? = nil
    var quietHoursEnd: String? = nil
    var timezone: String
}

struct PushSubscriptionKeys: Codable, Equatable, Hashable, Sendable {
    var p256dh: String
    var auth: String
}

struct PushSubscriptionRequest: Codable, Equatable, Hashable, Sendable {
    var endpoint: String
    var keys: PushSubscriptionKeys
}

struct DeletePushSubscriptionRequest: Codable, Equatable, Hashable, Sendable {
    var endpoint: String
}

struct PushSubscriptionResponse: Codable, Equatable, Hashable, Sendable {
    var ok: Bool
    var testSent: Bool
}

enum NativePushEnvironment: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case development
    case production

    var id: String { rawValue }
}

enum NativePushLocale: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case en
    case de
    case fr
    case it

    var id: String { rawValue }
}

struct NativePushDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var token: String
    var installationID: UUID? = nil
    var environment: NativePushEnvironment
    var locale: NativePushLocale
    var deviceName: String? = nil
    var sendTest: Bool

    private enum CodingKeys: String, CodingKey {
        case token
        case installationID = "installationId"
        case environment
        case locale
        case deviceName
        case sendTest
    }
}

struct DeleteNativePushDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var token: String
}

struct LiveActivityDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID
    var token: String
    var environment: NativePushEnvironment
    var locale: NativePushLocale

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
        case token
        case environment
        case locale
    }
}

struct DeleteLiveActivityDeviceRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
    }
}

struct LiveActivityUpdateTokenRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID
    var activityID: String
    var parcelID: UUID
    var token: String
    var environment: NativePushEnvironment
    var locale: NativePushLocale

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
        case activityID = "activityId"
        case parcelID = "parcelId"
        case token
        case environment
        case locale
    }
}

struct DeleteLiveActivityUpdateTokenRequest: Codable, Equatable, Hashable, Sendable {
    var installationID: UUID
    var activityID: String

    private enum CodingKeys: String, CodingKey {
        case installationID = "installationId"
        case activityID = "activityId"
    }
}

enum SyncJobStatus: String, Codable, CaseIterable, Hashable, Sendable, Identifiable {
    case queued
    case running
    case succeeded
    case failed

    var id: String { rawValue }
}

struct SyncJobResponse: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var status: SyncJobStatus
    var packageID: UUID? = nil
    var requestedAt: String
    var startedAt: String? = nil
    var completedAt: String? = nil
    var result: SyncSummary? = nil
    var error: String? = nil

    private enum CodingKeys: String, CodingKey {
        case id
        case status
        case packageID = "packageId"
        case requestedAt
        case startedAt
        case completedAt
        case result
        case error
    }
}

struct SyncSummary: Codable, Equatable, Hashable, Sendable {
    var checked: Int? = nil
    var updated: Int? = nil
    var waiting: Int? = nil
    var errors: Int? = nil
    var unsupported: Int? = nil
    var notificationsSent: Int? = nil
    var notificationErrors: Int? = nil
    var subscriptionsExpired: Int? = nil
}

struct HealthResponse: Codable, Equatable, Hashable, Sendable {
    var ok: Bool
}

struct AccountExportAccount: Codable, Equatable, Hashable, Sendable, Identifiable {
    var id: UUID
    var email: String? = nil
}

struct CarrierData: Codable, Equatable, Hashable, Sendable {
    var activeTrackingCarrier: CarrierID? = nil
    var swissPostReady: Bool? = nil
}

extension Parcel {
    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        id = try values.decode(UUID.self, forKey: .id)
        trackingNumber = try values.decode(String.self, forKey: .trackingNumber)
        label = try values.decode(String.self, forKey: .label)
        carrier = try values.decode(CarrierID.self, forKey: .carrier)
        createdAt = try values.decode(String.self, forKey: .createdAt)
        expectedDelivery = try values.decodeIfPresent(String.self, forKey: .expectedDelivery)
        lastStatusText = try values.decodeIfPresent(String.self, forKey: .lastStatusText)
        lastSyncedAt = try values.decodeIfPresent(String.self, forKey: .lastSyncedAt)
        syncStatus = try values.decode(SyncStatus.self, forKey: .syncStatus)
        syncError = try values.decodeIfPresent(String.self, forKey: .syncError)
        trackingURL = try values.decodeIfPresent(String.self, forKey: .trackingURL)
        dpdPostcode = try values.decodeIfPresent(String.self, forKey: .dpdPostcode)
        carrierData = try values.decodeIfPresent(CarrierData.self, forKey: .carrierData)
        archivedAt = try values.decodeIfPresent(String.self, forKey: .archivedAt)
        notificationsMuted = try values.decode(Bool.self, forKey: .notificationsMuted)
        trackingEvents = try values.decodeIfPresent([TrackingEvent].self, forKey: .trackingEvents) ?? []
    }
}
